server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=//USER-SERVICE/prometheus, /actuator/prometheus

        - id: bank-account-service-route
          uri: lb://BANK-ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=//BANK-ACCOUNT-SERVICE/prometheus, /actuator/prometheus

        - id: bank-transaction-service-route
          uri: lb://BANK-TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - RewritePath=//BANK-TRANSACTION-SERVICE/prometheus, /actuator/prometheus


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30